# 配置文件映射表
# source = 仓库内路径（相对于 files/）
# target = 系统路径（支持 ~ 展开为 $HOME）
# stage  = script（安装脚本直接部署）| config（config-apps.sh 部署）

[[configs]]
source = "root/sudoers"
target = "/etc/sudoers"
stage  = "script"

[[configs]]
source = "root/sddm.conf"
target = "/etc/sddm.conf.d/sddm.conf"
stage  = "config"

[[configs]]
source = "eli/i3/config"
target = "~/.config/i3/config"
stage  = "config"
