#=============================================================================
# basic.toml --- basic configuration example for SpaceVim
# Copyright (c) 2016-2022 Wang Shidong & Contributors
# Author: Wang Shidong < wsdjeg at 163.com >
# URL: https://spacevim.org
# License: GPLv3
#=============================================================================

# All SpaceVim option below [option] section
[options]
    # set spacevim theme. by default colorscheme layer is not loaded,
    # if you want to use more colorscheme, please load the colorscheme
    # layer
    colorscheme = "onedark"
    colorscheme_bg = "dark"

    # Disable guicolors in basic mode, many terminal do not support 24bit
    # true colors
    enable_guicolors = true
    # Disable statusline separator, if you want to use other value, please
    # install nerd fonts
    statusline_separator = "fire"
    statusline_iseparator = "bar"
    buffer_index_type = 4
    windows_index_type = 3
    enable_tabline_filetype_icon = true
    enable_statusline_mode = true
    statusline_unicode = true
    # Enable vim compatible mode, avoid changing origin vim key bindings
    vimcompatible = true
    # filemanager = "defx"

# Enable autocomplete layer
[[layers]]
    name = 'autocomplete'
    auto_completion_return_key_behavior = "complete"
    auto_completion_tab_key_behavior = "cycle"

[[layers]]
    name = 'shell'
    default_position = 'top'
    default_height = 30

[[layers]]
    name = 'lang#lua'

[[layers]]
    name = 'lang#markdown'

[[layers]]
    name = 'leaderf'

[[layers]]
    name = 'git'

[[layers]]
    name = 'colorscheme'

[[layers]]
    name = 'core#banner'

[[layers]]
    name = 'core#statusline'

[[layers]]
    name = 'core#tabline'
 
[[layers]]
    name = 'core'
    filetree_show_hidden = true
    enable_smooth_scrolling = true

[[layers]]
    name = 'zettelkasten'

[[layers]]
    name = 'telescope'


[[custom_plugins]]
    repo = "ryanoasis/vim-devicons"
    merged = false

[[custom_plugins]]
    repo = "github/copilot.vim"
    merged = false
